apiVersion: v1
kind: Service
metadata:
    name: go-service
    namespace: dcim
    labels:
        app: go-service
spec:
    type: ClusterIP
    selector:
        app: go-service
    ports:
        - name: http
          port: 8080
          targetPort: 8080
          protocol: TCP
