apiVersion: v1
kind: Secret
metadata:
    name: network-ops-secret
    namespace: {{ include "dcim.namespace" . }}
    labels:
        {{- include "dcim.labels" . | nindent 8 }}
        app.kubernetes.io/component: network-ops
type: Opaque
data:
    DATABASE_URL: {{ include "dcim.databaseUrl" . | b64enc | quote }}
    INTERNAL_SECRET: {{ .Values.networkOps.secrets.INTERNAL_SECRET | b64enc | quote }}
