apiVersion: v1
kind: ConfigMap
metadata:
    name: core-api-config
    namespace: {{ include "dcim.namespace" . }}
    labels:
        {{- include "dcim.labels" . | nindent 8 }}
        app.kubernetes.io/component: core-api
data:
    PORT: {{ .Values.coreApi.service.port | quote }}
    GO_ENV: {{ .Values.global.environment | quote }}
