apiVersion: v1
kind: Secret
metadata:
    name: core-api-secret
    namespace: {{ include "dcim.namespace" . }}
    labels:
        {{- include "dcim.labels" . | nindent 8 }}
        app.kubernetes.io/component: core-api
type: Opaque
data:
    DATABASE_URL: {{ include "dcim.databaseUrl" . | b64enc | quote }}
    X_INTERNAL_SECRET: {{ .Values.coreApi.secrets.X_INTERNAL_SECRET | b64enc | quote }}
